runtime: python39
service: diplomacy
default_expiration: "1d"
app_engine_apis: true
handlers:
- url: /static
  static_dir: static
  expiration: "7d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301