runtime: python39
service: diplomacy
app_engine_apis: true
handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: auto
  login: required